// <auto-generated />
namespace CobanaEnergy.Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class EDFSME_86c59edwa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EDFSME_86c59edwa));
        
        string IMigrationMetadata.Id
        {
            get { return "202509031548518_EDFSME_86c59edwa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
