// <auto-generated />
namespace CobanaEnergy.Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Faryal_PolymorphicRelations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Faryal_PolymorphicRelations));
        
        string IMigrationMetadata.Id
        {
            get { return "202508180943056_Faryal_PolymorphicRelations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
