// <auto-generated />
namespace CobanaEnergy.Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Campaign_86c4btzgh_InitialMapping : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Campaign_86c4btzgh_InitialMapping));
        
        string IMigrationMetadata.Id
        {
            get { return "202508061207452_Campaign_86c4btzgh_InitialMapping"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
