// <auto-generated />
namespace CobanaEnergy.Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class testingAbdullahInitialMapping : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(testingAbdullahInitialMapping));
        
        string IMigrationMetadata.Id
        {
            get { return "202509051053196_testing-Abdullah-InitialMapping"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
