// <auto-generated />
namespace CobanaEnergy.Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class RenamingColumn86c5adwhx : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenamingColumn86c5adwhx));
        
        string IMigrationMetadata.Id
        {
            get { return "202509101403173_Renaming-Column-86c5adwhx"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
